package model;

       /** Inhouse Class */
public class InHousePart extends Part{

    private int machineID;

           /** InHouse Part Constructor.
            * Defines an InHouse part based on the below parameters
            * @param partID AutoGenerated ID Number of the new Inhouse Part
            * @param partName Name of the new Part
            * @param partPrice Price of the new Part
            * @param partInStock Inventory of the new Part
            * @param min Minimum Quantity of the new Part
            * @param max Maximum Quantity of the new Part
            * @param machineID Name of the Outsourced Producer of the new Part
            */
    public InHousePart(int partID, String partName, double partPrice, int partInStock, int min, int max, int machineID) {
        super(partID, partName,partPrice,partInStock,min,max);
        this.machineID = machineID;
    }

    public InHousePart() {
        super();
    }

       /** Gets Machine ID.
        *
        * @return Returns Machine ID
        */
    public int getMachineID() {
        return machineID;
    }

       /** Sets Machine ID.
        *
        * @param machineID Machine ID for Part menu's
        */
    public void setMachineID(int machineID) {
        this.machineID = machineID;
    }

}

