package model;

        /**Outsourced Class */
public class OutsourcedPart extends Part{

    private String companyName;

            /** Outsourced Part Constructor.
             *
             * Defines an Outsourced Part based on the values below
             * @param partID AutoGenerated ID Number of the new Outsourced Part
             * @param partName Name of the new Part
             * @param partPrice Price of the new Part
             * @param partInStock Inventory of the new Part
             * @param min Minimum Quantity of the new Part
             * @param max Maximum Quantity of the new Part
             * @param companyName Name of the Outsourced Producer of the new Part
             */
    public OutsourcedPart(int partID, String partName, double partPrice, int partInStock, int min, int max, String companyName) {
        super(partID,partName,partPrice,partInStock, min, max);
        this.companyName = companyName;
    }

    public OutsourcedPart() {
        super();
    }

            /** Gets Company Name - Same Textfield as Machine ID based on RadioButton Selection.
             *
             * @return Returns company name
             */
    public String getCompanyName() {
        return companyName;
    }

            /** Sets company name value.
             *
             * @param companyName - Same Textfield as Machine ID based on RadioButton Selection
             */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }



}


